In [3]:
import pandas as pd
import sys
import os
father_dir = os.path.abspath('..')
sys.path.insert(0, father_dir)
import src.features.build_features as bf

C:\Users\brjjo287\AppData\Local\Temp\ipykernel_21552\3516571886.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [4]:
train = pd.read_csv(rf'{father_dir}\data\external\simulated_listings1.csv')
test = pd.read_csv(rf'{father_dir}\data\external\target_apartments1.csv')

In [5]:
print(train.columns, '\n', test.columns)

Index(['rooms', 'garages', 'useful_area', 'latitude', 'longitude', 'value',
       'interior_quality', 'time_on_market', 'sold'],
      dtype='object')
 Index(['rooms', 'garages', 'useful_area', 'latitude', 'longitude', 'value',
       'interior_quality'],
      dtype='object')

In [7]:
# Threshold em quartos e garagens  # Quartos e garagem 4+
train.describe(percentiles=[0.05, 0.95, 0.99])

,rooms,garages,useful_area,latitude,longitude,value,interior_quality,time_on_market,sold
count,8369.000000,8369.000000,8369.000000,8369.000000,8369.000000,8.369000e+03,8369.00000,8369.000000,8369.000000
mean,2.839288,2.033098,145.138248,-23.578133,-46.666587,1.478881e+06,1.99534,114.661141,0.464213
std,0.895925,1.121227,88.908560,0.033659,0.034280,1.002856e+06,0.81680,95.152735,0.498747
min,1.000000,1.000000,25.000000,-23.647398,-46.739607,1.751010e+05,1.00000,0.097116,0.000000
5%,1.000000,1.000000,48.000000,-23.631059,-46.730893,4.245850e+05,1.00000,6.000000,0.000000
50%,3.000000,2.000000,120.000000,-23.576006,-46.665436,1.161620e+06,2.00000,88.030113,0.000000
95%,4.000000,4.000000,320.000000,-23.529389,-46.607742,3.668298e+06,3.00000,307.379102,1.000000
99%,4.000000,5.000000,433.640000,-23.497712,-46.575423,4.633386e+06,3.00000,350.189971,1.000000
max,8.000000,12.000000,826.000000,-23.491429,-46.567446,4.999430e+06,3.00000,359.820243,1.000000

In [6]:
train_processed = train.copy(deep=True)
train_processed.loc[train_processed['rooms'] >= 4, 'rooms'] = 4
train_processed.loc[train_processed['garages'] >= 4, 'garages'] = 4